### ISSUE TITLE
Suggestion: Automatic/scheduled sync

### ISSUE THREAD

**Issue by LucidUnrest** [marktaiwan/Philomena-Booru-Sync#1]
Idk if its possible, but an option to schedule automatic syncing would be awesome. Instead of having to do it manually every time.

**Comment by marktaiwan** [comment]
Feature implemented with c864600. Although, speaking as someone with perhaps a better than most's understanding of the robustness (or rather, the lack thereof) of the code, running the it periodically unsupervised is something I'd personally _strongly_ recommend against. But hey, you want to live dangerously that's your business ¯\\_(ツ)_/¯

On a side note, I hope the hiatus has been treating you well Lucid. I haven't forgotten about your other request yet, it's just progress has been bogged down due to my struggle with maintaining my motivation. I'll hopefully have it completed soon™.
